version: "3.3"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"

    volumes:
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
      - ./debug/debug.log:/var/www/html/wp-content/debug.log
      - ./.htaccess:/var/www/html/.htaccess

    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}

      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |-
        define('WP_HOME',   'http://projectname.localhost.test');
        define('WP_SITEURL','http://projectname.localhost.test');
        define('WP_DEBUG_DISPLAY', 0) ;
        define('WP_DEBUG_LOG',1);
volumes:
  db_data: {}
